[package]
name = "perceptor-pipeline"
description = "ECS pipeline, stages and plugins for the perceptor computer vision library"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
perceptor-core = { workspace = true, features = ["image", "ndarray"] }
perceptor-imgproc.workspace = true
bevy_ecs.workspace = true
image.workspace = true
ndarray.workspace = true
tracing.workspace = true

[dev-dependencies]
tempfile.workspace = true

[lints]
workspace = true
